apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: tekton-chains-example
spec:
  serviceAccountName: ""
  taskSpec:
    results:
    - name: TEST_URL
      type: string
    - name: TEST_DIGEST
      type: string
    steps:
    - name: create-image
      image: busybox
      script: |-
        #!/usr/bin/env sh
        echo 'gcr.io/foo/bar' | tee $(results.TEST_URL.path)
        echo "danbev-tekton-chains-example" | sha256sum | tr -d '-' | tee $(results.TEST_DIGEST.path)
