apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: basic-task
spec:
  params:
    - name: word
      description: The word to print
      default: bajja
      type: string
  steps:
    - name: print-command
      image: registry.access.redhat.com/ubi8/ubi
      args: ['-c', 'echo [basic-task]: $(params.word)']
      command:
        - /bin/bash
    - name: print-script
      image: registry.access.redhat.com/ubi8/ubi
      args: ['-c', 'echo $(params.word)']
      script: |
        #!/usr/bin/env bash
        echo "echo [basic-task] script $(params.word)"
